# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: daniel2025
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: message-board
# "service" is the name of this project. This will also be added to your AWS resource names.
service: message-board

stages:
  prod:
    observability: true
  default:
    observability: false
    params:
      userTableName: 'users-table-${sls:stage}'
      messageTableName: 'messages-table-${sls:stage}'
      boardTableName: 'boards-table-${sls:stage}'

provider:
  name: aws
  # default stage is dev
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  # the local aws profile to use to deploy
  profile: daniel_dev
  runtime: nodejs22.x
  deploymentMethod: direct
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [MessagesTable, Arn]
            - Fn::GetAtt: [BoardsTable, Arn]
  environment:
    USERS_TABLE: ${param:userTableName}
    MESSAGES_TABLE: ${param:messageTableName}
    BOARDS_TABLE: ${param:boardTableName}

functions:
  # API Gateway functions
  registerUser:
    handler: src/handlers/user.registerUser
    events:
      - httpApi:
          path: /users/register
          method: post

  getUserByEmail:
    handler: src/handlers/user.getUserByEmail
    events:
      - httpApi:
          path: /users/{email}
          method: get

  listBoards:
    handler: src/handlers/board.listBoards
    events:
      - httpApi:
          path: /boards
          method: get

  createBoard:
    handler: src/handlers/board.createBoard
    events:
      - httpApi:
          path: /boards
          method: post

  postMessage:
    handler: src/handlers/message.postMessage
    events:
      - httpApi:
          path: /boards/{boardId}/messages
          method: post

  # Event driven functions
  processUserRegistration:
    handler: src/handlers/processors.processUserRegistration
    events:
      - sns:
          topicName: 'user-registration'
          displayName: 'User Registration'

  processBoardCreation:
    handler: src/handlers/processors.processBoardCreation
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - BoardCreationQueue
              - Arn

  processMessagePosting:
    handler: src/handlers/processors.processMessagePosting
    events:
      - sns:
          topicName: 'message-posting'
          displayName: 'Message Posting'

resources:
  Resources:
    # users table
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:userTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    # boards table
    BoardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:boardTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE

    # messages table
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:messageTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: boardId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: topic
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: boardId-index
            KeySchema:
              - AttributeName: boardId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: topic-index
            KeySchema:
              - AttributeName: topic
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    # SQS queue for board creation
    BoardCreationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: 'board-creation-queue-${sls:stage}'

plugins:
  - serverless-offline
